name: Update Stocks Data

on:
  schedule:
    # 每天 UTC 时间 7:30 执行（东八区是 UTC+8，即 15:30）
    - cron: '30 7 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
        
    - name: Run update script
      run: python scripts/update_stocks.py data/stocks.json
      
    - name: Commit and push changes (if any)
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/stocks.json
        git diff --quiet && git diff --staged --quiet || git commit -m "chore: auto-update stocks.json"
        git push
